version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Kingkokl9@
      MYSQL_DATABASE: url_shortener
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    command: ["npm", "start"]

  # Alag service for Drizzle Studio
  drizzle-studio:
    build: .
    ports:
      - "4998:4998"  # Different port use karo
    depends_on:
      - db
    env_file:
      - .env
    command: ["npx", "drizzle-kit", "studio", "--port", "4998", "--host", "0.0.0.0"]

volumes:
  db_data: